# Generated by Django 5.1.5 on 2025-06-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
