# Generated by Django 5.1.5 on 2025-06-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0003_alter_favorites_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorites",
        ),
    ]
