# Generated by Django 5.1.5 on 2025-02-22 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_customer_alter_profile_user_delete_user"),
        ("favorites", "0002_alter_favorites_user"),
        ("recipes", "0003_alter_recipe_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="User_customer",
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
