# Generated by Django 5.1.5 on 2025-06-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_parent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecipeCategory",
        ),
    ]
