# Generated by Django 5.1.5 on 2025-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_parent"),
        ("recipes", "0003_alter_recipe_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="categories.category"
            ),
        ),
    ]
